Просмотрено %d клеток.
Найден путь из %d клеток.
Поиск прекращен.
Для повторения нажмите "Ввод" (Enter), для выхода - "Отказ" (Esc).
                         ИТОГОВАЯ СВОДКА
                Размер области был %d x %d клеток.
                               Завершенные игры   Прерванные игры
Число партий                         %3d               %3d
Просмотрено клеток, в среднем        %3d               %3d
Длина найденного пути, средняя       %3d                 -
